#!/bin/bash
#"$@" & # Run the command passed as arguments
#footclient --app-id=pulsemixerxxxxxxxxxxxxx -e pulsemixer &
#
#swaymsg [app_id="pulsemixerxxxxxxxxxxxxx"] floating enable # Toggles floating on the *focused* window (which should be the new app)
swaymsg -q 'exec footclient -a floatingpulsemixerxxxxx -e pulsemixer'
#i3-msg -m -t subscribe '["pulsemixerxxx"]'
