#!/bin/bash
#"$@" & # Run the command passed as arguments
xterm -e pulsemixer &
sleep 0.2                                        # Short delay for the window to register
i3-msg [title="pulsemixer"] "floating toggle" -q # Toggles floating on the *focused* window (which should be the new app)

#i3-msg -m -t subscribe '["pulsemixerxxx"]'
